#!/bin/sh
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# common name for the certificate - SANs don't matter here
URL="your.site.org"

# location of the certificates
SOURCE="/etc/ssl/letsencrypt/$URL"

# active cert issue date
ACTIVECERT=`echo | openssl s_client -connect 127.0.0.1:443 2>/dev/null | openssl x509 -noout -startdate`

# current file cert issue date
NEWCERT=`cat $SOURCE/cert.pem | openssl x509 -noout -startdate`

# check if certificate has been updated
if [ "$ACTIVECERT" != "$NEWCERT" ]
then
  # restart services - apache2 example
  service apache2 reload
fi
